server:
  port: 1200
eureka:
  client:
    serviceUrl:
      defaultZone: http://admin:123456@localhost:1001/eureka/

# 关闭安全管理
management:
  security:
    enabled: false
endpoints:
  health:
    sensitive: false
